(()=>{
  const portal=document.getElementById('portal'),nav=portal?.querySelector('.stamp-bottom-nav');
  if(!portal||!nav)return;
  const schedulePanel=document.getElementById('scheduleView'),panel=document.createElement('section');
  panel.className='card absence-view';panel.id='absenceView';panel.hidden=true;
  panel.innerHTML=`<h2>Urlaub & Krankmeldung</h2><p class="absence-note">Deine Meldung wird direkt dem angemeldeten Mitarbeiter zugeordnet und im CRM angezeigt.</p><div class="absence-switch"><button type="button" class="active" data-absence-type="Urlaub">Urlaub beantragen</button><button type="button" data-absence-type="Krank">Krank melden</button></div><form id="absenceForm"><input type="hidden" name="typ" value="Urlaub"><div class="absence-dates"><label>Von<input name="von" type="date" required></label><label>Bis<input name="bis" type="date" required></label></div><label>Hinweis (optional)<textarea name="notiz" rows="3" maxlength="500" placeholder="Kurzer Hinweis für den Betrieb"></textarea></label><div class="absence-info" id="absenceInfo">Der Urlaub wird als Antrag eingetragen und kann anschließend im CRM geprüft werden.</div><button type="submit" id="absenceSubmit">Urlaubsantrag senden</button></form><div class="absence-list"><h2>Meine Meldungen</h2><div id="absenceItems"><span>Noch keine Meldungen geladen.</span></div></div>`;
  schedulePanel.after(panel);nav.style.gridTemplateColumns='repeat(4,1fr)';nav.insertAdjacentHTML('beforeend','<button type="button" data-stamp-view="absence"><b>✚</b><span>Abwesenheit</span></button>');
  const views={stamp:document.getElementById('stampView'),history:document.getElementById('historyView'),schedule:schedulePanel,absence:panel};
  function show(view){Object.entries(views).forEach(([name,node])=>node.hidden=name!==view);nav.querySelectorAll('button').forEach(button=>button.classList.toggle('active',button.dataset.stampView===view));window.scrollTo({top:0,behavior:'smooth'})}
  nav.querySelectorAll('button').forEach(button=>button.onclick=()=>show(button.dataset.stampView));
  const form=document.getElementById('absenceForm'),typeInput=form.elements.typ,submit=document.getElementById('absenceSubmit'),info=document.getElementById('absenceInfo');
  const now=new Date(),today=[now.getFullYear(),String(now.getMonth()+1).padStart(2,'0'),String(now.getDate()).padStart(2,'0')].join('-');form.elements.von.value=today;form.elements.bis.value=today;
  panel.querySelectorAll('[data-absence-type]').forEach(button=>button.onclick=()=>{const type=button.dataset.absenceType;typeInput.value=type;panel.querySelectorAll('[data-absence-type]').forEach(item=>item.classList.toggle('active',item===button));submit.textContent=type==='Urlaub'?'Urlaubsantrag senden':'Krankmeldung senden';info.textContent=type==='Urlaub'?'Der Urlaub wird als Antrag eingetragen und kann anschließend im CRM geprüft werden.':'Die Krankmeldung wird sofort im CRM angezeigt. Eine Arbeitsunfähigkeitsbescheinigung wird hier nicht hochgeladen.'});
  let schedule=[];const safe=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  function groups(){const map=new Map();schedule.filter(item=>/urlaub|krank/i.test((item.tätigkeit||item.ttigkeit||'')+' '+(item.status||''))).forEach(item=>{const key=item.id||item.schichtid||`row-${item.row_index}`;if(map.has(key)){map.get(key).items.push(item);map.get(key).dates.push(item.datum)}else map.set(key,{items:[item],dates:[item.datum],title:item.tätigkeit||item.ttigkeit||'Abwesenheit',status:item.status||'Gemeldet'})});return [...map.values()].reverse()}
  function render(){const items=groups(),host=document.getElementById('absenceItems');host.innerHTML=items.length?items.slice(0,30).map(group=>{const dates=group.dates.slice(),range=dates.length>1?`${dates[0]} – ${dates.at(-1)}`:dates[0],approved=/urlaub genehmigt/i.test(group.status),pending=/stornierung beantragt/i.test(group.status),cancelled=/urlaub storniert/i.test(group.status),row=group.items[0].row_index;return `<article class="absence-item ${/krank/i.test(group.title+' '+group.status)?'sick':'vacation'}"><div><b>${safe(group.title)}</b><span>${safe(range||'')}</span><small>${safe(group.status)}</small></div>${approved?`<button type="button" class="absence-cancel" onclick="requestAbsenceCancellation(${Number(row)},this)">Stornierung anfragen</button>`:pending?'<em>Stornierung wird geprüft</em>':cancelled?'<em>Storniert</em>':''}</article>`}).join(''):'<span>Noch keine Urlaubs- oder Krankmeldung vorhanden.</span>'}
  window.requestAbsenceCancellation=async(row,button)=>{if(!confirm('Möchtest du für diesen genehmigten Urlaub eine Stornierung anfragen?'))return;button.disabled=true;button.textContent='Wird gesendet …';el('notice').textContent='Stornierungsanfrage wird gesendet …';try{const result=await api('reinico_absence_cancel',{row_index:String(row)});schedule=Array.isArray(result.schedule)?result.schedule:schedule;render();el('notice').textContent=result.message||'Stornierungsanfrage wurde gesendet.'}catch(error){button.disabled=false;button.textContent='Stornierung anfragen';el('notice').textContent=error.message}};
  const previousDraw=draw;draw=function(result){schedule=Array.isArray(result.schedule)?result.schedule:[];previousDraw(result);render()};
  form.onsubmit=async event=>{event.preventDefault();if(form.elements.bis.value<form.elements.von.value){el('notice').textContent='Das Enddatum darf nicht vor dem Startdatum liegen.';return}submit.disabled=true;el('notice').textContent=typeInput.value==='Urlaub'?'Urlaubsantrag wird gespeichert …':'Krankmeldung wird gespeichert …';try{const result=await api('reinico_absence',{typ:typeInput.value,von:form.elements.von.value,bis:form.elements.bis.value,notiz:form.elements.notiz.value.trim()});schedule=Array.isArray(result.schedule)?result.schedule:schedule;render();form.elements.notiz.value='';el('notice').textContent=result.message||'Meldung gespeichert.'}catch(error){el('notice').textContent=error.message}finally{submit.disabled=false}};
  const style=document.createElement('style');style.textContent=`.absence-view h2{margin:0 0 5px}.absence-note{margin:0 0 17px;color:#94a3b8;font-size:13px;line-height:1.5}.absence-switch{display:grid;grid-template-columns:1fr 1fr;gap:7px;padding:5px;background:#0f172a;border-radius:13px}.absence-switch button{margin:0;background:transparent;color:#94a3b8;font-size:13px}.absence-switch button.active{background:#2563a6;color:#fff}.absence-dates{display:grid;grid-template-columns:1fr 1fr;gap:10px}.absence-view textarea{width:100%;margin-top:6px;padding:13px;border:1px solid #475569;border-radius:12px;background:#25354b;color:#fff;font:inherit}.absence-info{margin:13px 0;padding:11px;border:1px solid #475569;border-radius:10px;color:#cbd5e1;font-size:12px}.absence-list{margin-top:24px;padding-top:18px;border-top:1px solid #334155}.absence-list>h2{font-size:15px}.absence-item{display:flex;justify-content:space-between;align-items:center;gap:10px;padding:11px 12px;margin-top:7px;border-left:4px solid #d2820b;border-radius:9px;background:#0f172a}.absence-item.sick{border-left-color:#c83b45}.absence-item div{display:grid;gap:3px}.absence-item span,.absence-item small,.absence-item em{color:#94a3b8;font-size:11px}.absence-item em{font-style:normal}.absence-cancel{width:auto;margin:0;padding:8px 10px;border:1px solid #f59e0b;background:transparent;color:#fbbf24;font-size:11px;white-space:nowrap}@media(max-width:350px){.absence-dates{grid-template-columns:1fr}}`;document.head.append(style);render();
})();
