(()=>{
  const portal=document.getElementById('portal');if(!portal)return;
  const safe=value=>String(value??'').replace(/[&<>"']/g,character=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[character]));
  const stampPanel=portal.querySelector(':scope>.card:first-child'),historyPanel=portal.querySelector(':scope>.card:nth-of-type(2)'),printButton=document.getElementById('printHistory');
  stampPanel.id='stampView';historyPanel.id='historyView';historyPanel.append(printButton);
  const schedulePanel=document.createElement('section');schedulePanel.className='card stamp-schedule';schedulePanel.id='scheduleView';schedulePanel.hidden=true;schedulePanel.innerHTML='<h2>Mein Schichtplan</h2><p class="schedule-note">Hier erscheinen deine im CRM geplanten Einsätze.</p><div id="employeeSchedule"><div class="schedule-empty">Schichtplan wird geladen …</div></div>';historyPanel.after(schedulePanel);
  const nav=document.createElement('nav');nav.className='stamp-bottom-nav';nav.setAttribute('aria-label','Bereiche');nav.innerHTML='<button type="button" data-stamp-view="stamp" class="active"><b>◷</b><span>Stempeln</span></button><button type="button" data-stamp-view="history"><b>▤</b><span>Verlauf</span></button><button type="button" data-stamp-view="schedule"><b>▦</b><span>Schichtplan</span></button>';portal.append(nav);
  function showStampView(view){stampPanel.hidden=view!=='stamp';historyPanel.hidden=view!=='history';schedulePanel.hidden=view!=='schedule';nav.querySelectorAll('button').forEach(button=>button.classList.toggle('active',button.dataset.stampView===view));window.scrollTo({top:0,behavior:'smooth'})}
  nav.querySelectorAll('button').forEach(button=>button.onclick=()=>showStampView(button.dataset.stampView));
  function scheduleDateValue(value){const text=String(value||'').trim(),m=text.match(/^(\d{1,2})\.(\d{1,2})\.(\d{4})/);if(m)return new Date(+m[3],+m[2]-1,+m[1]);const date=new Date(text);return Number.isNaN(date.getTime())?null:date}
  function renderEmployeeSchedule(items){const host=document.getElementById('employeeSchedule');if(!host)return;items=Array.isArray(items)?items:[];items.sort((a,b)=>(scheduleDateValue(a.datum)?.getTime()||0)-(scheduleDateValue(b.datum)?.getTime()||0));if(!items.length){host.innerHTML='<div class="schedule-empty"><b>Keine Einsätze eingetragen.</b><span>Sobald im CRM ein Einsatz geplant wird, erscheint er hier.</span></div>';return}host.innerHTML=items.map(item=>{const date=scheduleDateValue(item.datum),dateText=date?date.toLocaleDateString('de-DE',{weekday:'short',day:'2-digit',month:'2-digit',year:'numeric'}):String(item.datum||'Datum offen'),time=[item.beginn,item.ende].filter(Boolean).join(' – ')||'Zeit noch offen';return `<article class="employee-shift"><div class="shift-date"><b>${safe(dateText)}</b><span>${safe(time)}</span></div><div><strong>${safe(item.objekt||item.tätigkeit||'Einsatz')}</strong><small>${safe(item.tätigkeit||item.status||'Geplant')}</small></div><span class="shift-status">${safe(item.status||'Geplant')}</span></article>`}).join('')}
  let scheduleItems=[];const previousDraw=draw;draw=function(result){scheduleItems=result.schedule||[];previousDraw(result);renderEmployeeSchedule(scheduleItems)};
  const style=document.createElement('style');style.textContent=`body{padding-bottom:105px}.stamp-bottom-nav{position:fixed;z-index:50;left:50%;bottom:max(10px,env(safe-area-inset-bottom));transform:translateX(-50%);display:grid;grid-template-columns:repeat(3,1fr);gap:5px;width:min(450px,calc(100% - 24px));padding:7px;background:#182338ee;border:1px solid #475569;border-radius:17px;box-shadow:0 14px 34px #020617cc;backdrop-filter:blur(14px)}.stamp-bottom-nav button{display:grid;justify-items:center;gap:2px;margin:0;padding:8px 5px;background:transparent;color:#94a3b8;border-radius:11px;font-size:11px}.stamp-bottom-nav button b{font-size:20px;line-height:1}.stamp-bottom-nav button.active{background:#2563a6;color:#fff}.stamp-schedule h2{margin-bottom:4px}.schedule-note{margin:0 0 16px;color:#94a3b8;font-size:13px}.employee-shift{display:grid;grid-template-columns:125px 1fr auto;gap:12px;align-items:center;padding:14px 0;border-bottom:1px solid #334155}.employee-shift:last-child{border-bottom:0}.shift-date,.employee-shift>div:nth-child(2){display:grid;gap:4px}.shift-date span,.employee-shift small{color:#94a3b8;font-size:11px}.shift-status{padding:5px 8px;border-radius:999px;background:#1e3a5f;color:#93c5fd;font-size:10px;font-weight:800}.schedule-empty{display:grid;gap:6px;padding:28px 16px;text-align:center;color:#94a3b8;border:1px dashed #475569;border-radius:13px}.schedule-empty b{color:#e2e8f0}#historyView #printHistory{margin-top:16px}@media(max-width:390px){.employee-shift{grid-template-columns:1fr auto}.shift-date{grid-column:1/-1}}`;document.head.append(style);
  showStampView('stamp');
})();
