(()=>{
  const portal=document.getElementById('portal'),nav=portal?.querySelector('.stamp-bottom-nav');
  if(!portal||!nav)return;
  const schedulePanel=document.getElementById('scheduleView');
  const panel=document.createElement('section');panel.className='card absence-view';panel.id='absenceView';panel.hidden=true;
  panel.innerHTML=`<h2>Urlaub & Krankmeldung</h2><p class="absence-note">Deine Meldung wird direkt dem angemeldeten Mitarbeiter zugeordnet und im CRM angezeigt.</p><div class="absence-switch"><button type="button" class="active" data-absence-type="Urlaub">Urlaub beantragen</button><button type="button" data-absence-type="Krank">Krank melden</button></div><form id="absenceForm"><input type="hidden" name="typ" value="Urlaub"><div class="absence-dates"><label>Von<input name="von" type="date" required></label><label>Bis<input name="bis" type="date" required></label></div><label>Hinweis (optional)<textarea name="notiz" rows="3" maxlength="500" placeholder="Kurzer Hinweis für den Betrieb"></textarea></label><div class="absence-info" id="absenceInfo">Der Urlaub wird als Antrag eingetragen und kann anschließend im CRM geprüft werden.</div><button type="submit" id="absenceSubmit">Urlaubsantrag senden</button></form><div class="absence-list"><h2>Meine Meldungen</h2><div id="absenceItems"><span>Noch keine Meldungen geladen.</span></div></div>`;
  schedulePanel.after(panel);
  nav.style.gridTemplateColumns='repeat(4,1fr)';
  nav.insertAdjacentHTML('beforeend','<button type="button" data-stamp-view="absence"><b>✚</b><span>Abwesenheit</span></button>');
  const views={stamp:document.getElementById('stampView'),history:document.getElementById('historyView'),schedule:schedulePanel,absence:panel};
  function show(view){Object.entries(views).forEach(([name,node])=>node.hidden=name!==view);nav.querySelectorAll('button').forEach(button=>button.classList.toggle('active',button.dataset.stampView===view));window.scrollTo({top:0,behavior:'smooth'})}
  nav.querySelectorAll('button').forEach(button=>button.onclick=()=>show(button.dataset.stampView));
  const form=document.getElementById('absenceForm'),typeInput=form.elements.typ,submit=document.getElementById('absenceSubmit'),info=document.getElementById('absenceInfo');
  const today=new Date(),todayIso=[today.getFullYear(),String(today.getMonth()+1).padStart(2,'0'),String(today.getDate()).padStart(2,'0')].join('-');form.elements.von.value=todayIso;form.elements.bis.value=todayIso;
  panel.querySelectorAll('[data-absence-type]').forEach(button=>button.onclick=()=>{const type=button.dataset.absenceType;typeInput.value=type;panel.querySelectorAll('[data-absence-type]').forEach(item=>item.classList.toggle('active',item===button));submit.textContent=type==='Urlaub'?'Urlaubsantrag senden':'Krankmeldung senden';info.textContent=type==='Urlaub'?'Der Urlaub wird als Antrag eingetragen und kann anschließend im CRM geprüft werden.':'Die Krankmeldung wird sofort im CRM angezeigt. Eine Arbeitsunfähigkeitsbescheinigung wird hier nicht hochgeladen.'});
  let schedule=[];
  const safe=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  function render(){const items=schedule.filter(item=>/urlaub|krank/i.test((item.tätigkeit||'')+' '+(item.status||''))).sort((a,b)=>String(b.datum||'').localeCompare(String(a.datum||''),'de'));document.getElementById('absenceItems').innerHTML=items.length?items.slice(0,30).map(item=>`<article class="absence-item ${/krank/i.test((item.tätigkeit||'')+' '+(item.status||''))?'sick':'vacation'}"><div><b>${safe(item.tätigkeit||'Abwesenheit')}</b><span>${safe(item.datum||'')}</span></div><small>${safe(item.status||'Gemeldet')}</small></article>`).join(''):'<span>Noch keine Urlaubs- oder Krankmeldung vorhanden.</span>'}
  const previousDraw=draw;draw=function(result){schedule=Array.isArray(result.schedule)?result.schedule:[];previousDraw(result);render()};
  form.onsubmit=async event=>{event.preventDefault();if(form.elements.bis.value<form.elements.von.value){el('notice').textContent='Das Enddatum darf nicht vor dem Startdatum liegen.';return}submit.disabled=true;el('notice').textContent=typeInput.value==='Urlaub'?'Urlaubsantrag wird gespeichert …':'Krankmeldung wird gespeichert …';try{const result=await api('reinico_absence',{typ:typeInput.value,von:form.elements.von.value,bis:form.elements.bis.value,notiz:form.elements.notiz.value.trim()});schedule=Array.isArray(result.schedule)?result.schedule:schedule;render();form.elements.notiz.value='';el('notice').textContent=result.message||'Meldung gespeichert.'}catch(error){el('notice').textContent=error.message}finally{submit.disabled=false}};
  const style=document.createElement('style');style.textContent=`.absence-view h2{margin:0 0 5px}.absence-note{margin:0 0 17px;color:#94a3b8;font-size:13px;line-height:1.5}.absence-switch{display:grid;grid-template-columns:1fr 1fr;gap:7px;padding:5px;background:#0f172a;border-radius:13px}.absence-switch button{margin:0;background:transparent;color:#94a3b8;font-size:13px}.absence-switch button.active{background:#2563a6;color:#fff}.absence-dates{display:grid;grid-template-columns:1fr 1fr;gap:10px}.absence-view textarea{width:100%;margin-top:6px;padding:13px;border:1px solid #475569;border-radius:12px;background:#25354b;color:#fff;font:inherit;resize:vertical}.absence-info{margin:13px 0;padding:11px;border:1px solid #475569;border-radius:10px;color:#cbd5e1;font-size:12px;line-height:1.5}.absence-list{margin-top:24px;padding-top:18px;border-top:1px solid #334155}.absence-list>h2{font-size:15px;margin-bottom:10px}.absence-item{display:flex;justify-content:space-between;align-items:center;gap:10px;padding:11px 12px;margin-top:7px;border-left:4px solid #d2820b;border-radius:9px;background:#0f172a}.absence-item.sick{border-left-color:#c83b45}.absence-item div{display:grid;gap:3px}.absence-item span,.absence-item small{color:#94a3b8;font-size:11px}@media(max-width:350px){.absence-dates{grid-template-columns:1fr}.stamp-bottom-nav button span{font-size:9px}}`;document.head.append(style);
  render();
})();
